https://www.pyimagesearch.com/2018/07/23/simple-object-tracking-with-opencv/

In [78]:
from scipy.spatial import distance as dist
import numpy as np
np.random.seed(42)


In [79]:
objectCentroids = np.random.uniform(size=(2, 2))
objectCentroids

array([[0.37, 0.95],
       [0.73, 0.6 ]])

In [80]:
centroids = np.random.uniform(size=(3, 2))
centroids

array([[0.16, 0.16],
       [0.06, 0.87],
       [0.6 , 0.71]])

In [81]:
D = dist.cdist(objectCentroids, centroids)
D.shape


(2, 3)

The result is a matrix D  of distances with 
 - two rows = # of existing object centroids
 - three columns = # of new input centroids

In [82]:
D

array([[0.82, 0.33, 0.33],
       [0.73, 0.73, 0.17]])

In [83]:
D.min(axis=1) #we find the minimum value for each row

array([0.33, 0.17])

In [91]:
rows = D.min(axis=1).argsort() #sorting on these values
print("Rows result :{}".format(rows)) # obtain the indexes of these rows

Rows result :[1 0]


- the second row (index 1 ) has the smallest value 
- the first row (index 0 ) has the next smallest value

In [88]:
D.argmin(axis=1) # find the index of the value with the smallest column

array([1, 2])

In [92]:
cols = D.argmin(axis=1)[rows] #sort these values using our existing rows
print("Cols result :{}".format(cols))

Cols result :[2 1]


In [90]:
print(list(zip(rows, cols))) #The final step is to combine them using zip

[(1, 2), (0, 1)]


## 분석 결과 

D[1, 2]  has the smallest Euclidean distance implying that 
- the second **existing object** will be matched against the third **input centroid**.

D[0, 1]  has the next smallest Euclidean distance which implies that 
- the first **existing object** will be matched against the second **input centroid**.